---
- name: Provision replica set nodes
  hosts: arbiters
  gather_facts: no
  sudo: yes

  tasks:
    - name: Configure arbiter without auth
      template:
        src: ../templates/arbiter-noauth.j2
        dest: /etc/mongod.conf
        owner: root
        group: root
        mode: "0644"
      with_items:
        - {
            data_dir: "{{ arb_data_dir }}",
            rs: "{{ rs[hostvars[inventory_hostname]['name']] }}",
            local_ip: "{{ hostvars[inventory_hostname]['name'] }}.c.{{ gcp_project }}.internal",
          }

    - name: Restart the mongod service
      service:
        name: mongod
        state: restarted
