---
- name: Provision mongos
  hosts: mongos
  gather_facts: yes
  sudo: yes

  tasks:
    - name: Configure mongod with auth
      template:
        src: ../templates/mongos.j2
        dest: /etc/mongod.conf
        owner: root
        group: root
        mode: "0644"
      with_items:
        - {
            config_server: "{{ config_server }}",
            local_ip: "{{ hostvars[inventory_hostname]['name'] }}.c.{{ gcp_project }}.internal",
            data_dir: "{{ arb_data_dir }}",
          }

    - name: Copy mongos service configuration
      copy:
        src: ./files/mongos.service
        dest: /lib/systemd/system/mongod.service
        owner: root
        group: root
        mode: "0600"
        force: yes

    - name: Force systemd to reread configs
      systemd:
        daemon_reload: yes

    - name: Restart the mongod service
      service:
        name: mongod
        state: restarted
        masked: no

    - name: Wait 10 seconds until mongos is available
      wait_for_connection:
        delay: 10

    - name: Add shard(s)
      shell: /usr/bin/mongo "mongodb://{{mongo_usr}}:{{mongo_pw}}@{{ inventory_hostname }}:27017" --quiet --eval "sh.addShard(\"{{ item }}\")"
      args:
        executable: /bin/bash
      loop: "{{ shards }}"
